import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'getting-started',
    'architecture',
    {
      type: 'category',
      label: 'Web app',
      items: ['web/features', 'web/ai-drafting', 'web/architecture'],
    },
    {
      type: 'category',
      label: 'Server',
      items: ['server/overview', 'server/api', 'server/configuration', 'server/security'],
    },
    'cli',
    'daemon',
    'mcp',
    {
      type: 'category',
      label: 'AI',
      items: ['ai/providers', 'ai/streaming-and-cost'],
    },
    {
      type: 'category',
      label: 'Conceptions',
      // Autogenerated: a new note is a new file, and never a line in this list.
      items: [{ type: 'autogenerated', dirName: 'conceptions' }],
    },
  ],
}

export default sidebars
